target_repositories: # owner/repository
  - rails/rails # sample

target_manager: # target manager file
  - requirements.txt # python
  - Gemfile # ruby
  - package.json # javascript

output: # output_type: output_path
  csv: test_output.csv
  # text: test_output.txt

info_license: True # get license info or not
info_author: True
info_homepage_url: True
info_code_url: True
